config/routes.rb
Rails.application.routes.draw do
  get '/search', to: "search#index"

  get 'moderation/index'
  patch 'moderation/update/:id', to: "moderation#update"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :albums
  resources :playlists
  post "/playlists/add", to: "playlists#add"
  resources :genres
  resources :music

  root "music#index"

  devise_for :users, 
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :users do
    # fixes redirect on error in form submission on new_user_registration_path
    get '/users', to: 'devise/registrations#new'
    get '/users/profile', to: 'users/profiles#edit'
    post '/users/profile/:id/edit', to: 'users/profiles#update'
  end
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id               :bigint           not null, primary key
#  color            :string           not null
#  cover_image_data :text
#  music_file_data  :text             not null
#  published        :boolean          default(FALSE)
#  title            :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  album_id         :bigint
#  artist_id        :bigint           not null
#
# Indexes
#
#  index_songs_on_album_id   (album_id)
#  index_songs_on_artist_id  (artist_id)
#
# Foreign Keys
#
#  fk_rails_...  (album_id => albums.id)
#  fk_rails_...  (artist_id => users.id)
#
class Song < ApplicationRecord
  validates_presence_of :color, :title, :music_file, :cover_image

  belongs_to :artist, class_name: "User"
  belongs_to :album, optional: true

  has_and_belongs_to_many :playlists
  has_and_belongs_to_many :genres

  scope :latest, -> { where(published: true).order(updated_at: :desc) }

  include CoverImage
  include SongUploader::Attachment(:music_file)
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  before_action :authenticate_user!, only: %i[ new create ]
  before_action :set_song, only: %i[ show edit update ]

  def index
    @songs = Song.latest
    @playlists = current_user&.playlists&.where&.not(id: nil) || []
    @genres = Genre.all
  end

  def show
  end

  def new
    @song = current_user.songs.new
    @genres = Genre.all.select(:title, :id).pluck(:title, :id)
    @albums = current_user.albums.select(:name, :id).pluck(:name, :id)
  end

  def edit
    @genres = Genre.all.select(:title, :id).pluck(:title, :id)
    @albums = current_user.albums.select(:name, :id).pluck(:name, :id)
  end

  def create
    @song = current_user.songs.build(song_params)

    if @song.save
      redirect_to root_path, notice: "Your music is uploaded!"
    else
      render :new, notice: "Music upload failed.", status: :unprocessable_entity
    end
  end

  def update
    if @song.update(song_params) 
      redirect_to root_path, notice: "Your music is uploaded!"
    else
      render :edit, notice: "Music update failed.", status: :unprocessable_entity
    end
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :cover_image, :music_file, :color, :album_id, :genre_ids)
  end
end

app/helpers/music_helper.rb
module MusicHelper
  def hex_color_to_rgba(hex, opacity)
    rgb = rgb_from_hex(hex)

    "rgba(#{rgb.join(", ")}, #{opacity})"
  end

  def text_color_from_bg(hex)
    rgb = rgb_from_hex(hex)
    red = rgb[0]
    green = rgb[1]
    blue = rgb[2]

    if (red*0.299 + green*0.587 + blue*0.114) > 186 
      return "#000000"
    else 
      return "#ffffff"
    end
  end

  private

  def rgb_from_hex(hex)
    hex.match(/^#(..)(..)(..)$/).captures.map(&:hex)
  end
end

app/views/music/_card.html.erb
<div data-controller="modal" data-modal-song-value="<%= song.id %>">
  <%= button_to music_path(song),
    method: :get,
    data: { turbo_frame: "video" },
    class: "relative rounded-lg w-72 h-72",
    style: "background: no-repeat center/cover url(#{song.cover_image_url});" do %> 
    <div 
      class="h-full w-full gradient relative rounded-lg"
      style="--gradient-from-color: <%= hex_color_to_rgba(song.color, 0.67) %>; --gradient-to-color: <%= hex_color_to_rgba("#000000", 0.2) %>;"
    >
      <div class="w-full p-4 absolute bottom-0 text-lg font-medium rounded-b-lg" style="background-color: <%= song.color %>;">
        <div class="flex items-center justify-between relative" data-controller="profile-badge">
          <p class="overflow-hidden whitespace-nowrap text-ellipsis" style="color: <%= text_color_from_bg(song.color) %>;">
            <abbr class="no-underline border-none" title="<%= song.title %>">
              <%= song.title %>
            </abbr>
          </p>
          <a class="cursor-pointer" data-action="click->profile-badge#click">
            <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24"><path fill="<%= text_color_from_bg(song.color) %>" d="M12 20Q11.175 20 10.588 19.413Q10 18.825 10 18Q10 17.175 10.588 16.587Q11.175 16 12 16Q12.825 16 13.413 16.587Q14 17.175 14 18Q14 18.825 13.413 19.413Q12.825 20 12 20ZM12 14Q11.175 14 10.588 13.412Q10 12.825 10 12Q10 11.175 10.588 10.587Q11.175 10 12 10Q12.825 10 13.413 10.587Q14 11.175 14 12Q14 12.825 13.413 13.412Q12.825 14 12 14ZM12 8Q11.175 8 10.588 7.412Q10 6.825 10 6Q10 5.175 10.588 4.588Q11.175 4 12 4Q12.825 4 13.413 4.588Q14 5.175 14 6Q14 6.825 13.413 7.412Q12.825 8 12 8Z"/></svg>
          </a>
          <div data-profile-badge-target="menu" data-modal-target="menu" class="hidden absolute left-full bottom-0 z-10 min-w-[100px] w-full bg-gray-700 text-base z-50 p-1 list-none divide-y divide-gray-100 rounded shadow my-2" id="dropdown">
              <ul aria-labelledby="dropdown">
                <% if current_user && song.artist_id == current_user.id %>
                  <li><%= link_to "Edit", edit_music_path(song), class: "text-sm hover:bg-gray-600 text-white block px-4 py-2" %></li>
                <% end %>
                <li>
                  <a data-action="click->modal#click" class="text-sm hover:bg-gray-600 text-white block px-4 py-2">Add to Playlist</a>
                </li>
              </ul>
           </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if current_user.present? %>
    <%= render layout: "layouts/modal", locals: { title: "Add Song to Playlist" } do %>
      <% if @playlists.present? %>
        <%= form_for :playlists_songs, url: playlists_add_path, method: :post do |f| %>
          <%= f.label :playlist, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
          <%= f.select :playlist_id, @playlists.select(:id, :name).pluck(:name, :id), {}, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>

          <%= f.hidden_field :song_id, {value: song.id} %>

          <%= f.submit "Add", class: "mt-4 py-2 px-3 bg-accent-200 rounded-md hover:bg-accent-700" %>
        <% end %>
      <% else %>
        <p class="text-grey-50 mb-4">
          You have no playlists.
        </p>
        <%= link_to "Create Playlist", new_playlist_path, class: "py-2 px-3 bg-accent-200 text-center rounded-md hover:bg-accent-700" %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/music/_form.html.erb
<div class="w-5/12">
  <% if song.errors.any? %>
    <div class="w-fit p-4 mb-4 text-sm text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800" role="alert">
      <ul>
        <% song.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for(song, url: url) do |f| %>
    <%= f.label :title, class: "block my-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
    <%= f.text_field :title, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>


    <%= f.label :cover_image, class: "block my-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
    <%= f.file_field :cover_image, class: "p-2.5 block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" %>
    <div class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="user_avatar_help">A cover image will be shown while displaying this song.</div>


    <%= f.label :music_file, class: "block my-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
    <%= f.file_field :music_file, class: "p-2.5 block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" %>


    <%= f.label :color, class: "block my-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
    <%= f.color_field :color, class: "block" %>
    <div class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="user_avatar_help">This color will be used to better style your music.</div>

    <% if @albums.present? %>
      <h5 class="my-3 font-rowdies text-2xl text-accent-400 font-bold">
        Select an Album
      </h5>

      <%= f.label :album, class: "block my-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
      <%= f.select :album_id, @albums, {}, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    <% else %>
      <h5 class="my-3 font-rowdies text-2xl text-accent-400 font-bold">
        You don't have any album
      </h5>

      <%= link_to "Create an Album", new_album_path, class: "block py-2 px-3 bg-accent-200 w-fit rounded-md hover:bg-accent-700" %>
      <div class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="user_avatar_help">Ignore it to create this song with no album.</div>
    <% end %>

    <%= f.label :genre, class: "block my-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
    <%= f.select :genre_ids, @genres, {}, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>

    <%= f.submit "Submit", class: "mt-4 py-2 px-3 bg-accent-200 rounded-md hover:bg-accent-700" %>
  <% end %>
</div>

app/views/music/edit.html.erb
<h3 class="mb-3 font-rowdies text-4xl text-accent-400 font-bold">
  Edit "<%= @song.title %>"
</h3>

<%= render "form", song: @song, url: music_path(@song) %>

app/views/music/index.html.erb
<div class="py-4 px-6 mb-6">
  <h3 class="mb-3 font-rowdies text-4xl text-accent-400 font-bold">
    Newly Released
  </h3>

  <div class="flex space-x-8 scrollable bar pb-2">
    <% @songs.each do |song| %>
      <%= render "card", song: song %>
    <% end %>
  </div>
</div>

<div class="py-4 px-6 mb-6">
  <h3 class="mb-3 font-rowdies text-4xl text-accent-400 font-bold">
    Genres
  </h3>
  <div class="flex space-x-8 scrollable bar pb-2">
    <% @genres.each do |genre| %>
      <div>
        <%= button_to genre_path(genre), method: :get, data: { turbo: false }, class: "rounded-lg w-72 h-72", style: "background: no-repeat center/cover url(#{genre.cover_image_url});" do %>
          <div 
            class="h-full w-full gradient relative rounded-lg"
            style="--gradient-from-color: <%= hex_color_to_rgba(genre.color, 0.67) %>; --gradient-to-color: <%= hex_color_to_rgba("#000000", 0.2) %>;"
          >
          <div class="w-full p-4 absolute bottom-0 text-lg font-medium rounded-b-lg" style="background-color: <%= genre.color %>;">
            <p class="overflow-hidden whitespace-nowrap text-ellipsis">
            <abbr class="no-underline border-none" style="color: <%= text_color_from_bg(genre.color) %>;" title="<%= genre.title %>">
              <%= genre.title %>
            </abbr>
            </p>
          </div>
          </div>
          <% end %>
      </div>
    <% end %>
  </div>
</div>

<br>
<br>
<br>


<% if @playlists.present? %>
  <div class="py-4 px-6">
    <h3 class="mb-3 font-rowdies text-4xl text-accent-400 font-bold">
      Top Playlists
    </h3>
  </div>
<% end %>

<%= render "components/player", song: @songs[0] %>

app/views/music/new.html.erb
<h3 class="mb-3 font-rowdies text-4xl text-accent-400 font-bold">
  Create a Song
</h3>

<%= render "form", song: @song, url: music_index_path %>

app/views/music/show.html.erb
<h1><%= @song.title %> </h1>

<%= turbo_frame_tag "video" do %>
<section data-controller="player" class="fixed bottom-0 left-0 w-screen bg-dark drop-shadow-lg">
  <video autoplay data-action="timeupdate->player#setTime durationchange->player#setDuration" data-player-target="video" class="hidden" src="<%= @song.music_file_url %>"></video>
  <div data-player-target="seekerParent" data-action="click->player#seek" class="range bg-gray-600 bg-[#303030] w-full h-1 cursor-pointer">
    <div data-player-target="bar" class="primary-range bg-accent-400 h-full" style="width: 0px"></div>
  </div>
  <div class="px-16 py-2">
  <div class="flex items-center justify-between">
    <div class="flex items-center">
      <img class="object-contain mr-4 h-20 w-20" src="<%= @song.cover_image_url %>" alt="">
      <div class="meta">
        <h5 class="font-bold text-md"><%= @song.title %></h5>
        <p class="text-gray-200 text-sm"><%= @song.artist.name %></p>
        <p data-player-target="timer" class="text-gray-200 text-sm"></p>
      </div>
    </div>
    <div class="player-controls flex">
      <button data-action="click->player#previous" class="prev">
        <svg xmlns="http://www.w3.org/2000/svg" height="48" width="48"><path fill="#fff" d="M11 36V12H14V36ZM37 36 19.7 24 37 12ZM34 24ZM34 30.25V17.75L24.95 24Z"/></svg>
      </button>
      <button data-player-target="playButton" data-action="click->player#playPause" class="play">
        <svg xmlns="http://www.w3.org/2000/svg" height="48" width="48"><path fill="#fff" d="M18.5 32H21.5V16H18.5ZM26.5 32H29.5V16H26.5ZM24 44Q19.9 44 16.25 42.425Q12.6 40.85 9.875 38.125Q7.15 35.4 5.575 31.75Q4 28.1 4 24Q4 19.9 5.575 16.25Q7.15 12.6 9.875 9.875Q12.6 7.15 16.25 5.575Q19.9 4 24 4Q28.1 4 31.75 5.575Q35.4 7.15 38.125 9.875Q40.85 12.6 42.425 16.25Q44 19.9 44 24Q44 28.1 42.425 31.75Q40.85 35.4 38.125 38.125Q35.4 40.85 31.75 42.425Q28.1 44 24 44ZM24 24Q24 24 24 24Q24 24 24 24Q24 24 24 24Q24 24 24 24Q24 24 24 24Q24 24 24 24Q24 24 24 24Q24 24 24 24ZM24 41Q31 41 36 36Q41 31 41 24Q41 17 36 12Q31 7 24 7Q17 7 12 12Q7 17 7 24Q7 31 12 36Q17 41 24 41Z"/></svg>
      </button>
      <button data-action="click->player#next" class="next">
        <svg xmlns="http://www.w3.org/2000/svg" height="48" width="48"><path fill="#fff" d="M34 36V12H37V36ZM11 36V12L28.3 24ZM14 24ZM14 30.25 23.05 24 14 17.75Z"/></svg>
      </button>
    </div>

    <div class="flex items-center">
      <button data-action="click->player#mute" data-player-target="volumeIcon">
        <svg xmlns="http://www.w3.org/2000/svg" height="40" width="40"><path fill="#fff" d="M23.333 34.542V31.667Q27.292 30.542 29.75 27.312Q32.208 24.083 32.208 19.958Q32.208 15.833 29.75 12.583Q27.292 9.333 23.333 8.25V5.375Q28.5 6.542 31.75 10.604Q35 14.667 35 19.958Q35 25.25 31.75 29.312Q28.5 33.375 23.333 34.542ZM5 25V15H11.667L20 6.667V33.333L11.667 25ZM22.792 26.875V13.042Q24.917 13.833 26.208 15.75Q27.5 17.667 27.5 20Q27.5 22.375 26.208 24.25Q24.917 26.125 22.792 26.875ZM17.208 13.583 12.875 17.792H7.792V22.208H12.875L17.208 26.458ZM13.208 20Z"/></svg>
      </button>
      <input
        data-action="input->player#handleVolume"
        data-player-target="volume"
        class="ml-1"
        type="range"
        min="0"
        max="1"
        step="0.05"
      />
    </div>
  </div>
  </div>
</section>
<% end %>