config/routes.rb
Rails.application.routes.draw do
  get '/search', to: "search#index"

  get 'moderation/index'
  patch 'moderation/update/:id', to: "moderation#update"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :albums
  resources :playlists
  post "/playlists/add", to: "playlists#add"
  resources :genres
  resources :music

  root "music#index"

  devise_for :users, 
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :users do
    # fixes redirect on error in form submission on new_user_registration_path
    get '/users', to: 'devise/registrations#new'
    get '/users/profile', to: 'users/profiles#edit'
    post '/users/profile/:id/edit', to: 'users/profiles#update'
  end
end

app/models/playlist.rb
# == Schema Information
#
# Table name: playlists
#
#  id               :bigint           not null, primary key
#  color            :string           not null
#  cover_image_data :text
#  is_public        :boolean          default(FALSE)
#  name             :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :bigint           not null
#
# Indexes
#
#  index_playlists_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Playlist < ApplicationRecord
  validates_presence_of :color, :name, :cover_image

  belongs_to :user
  has_and_belongs_to_many :songs

  scope :top, -> { where(is_public: true).order(updated_at: :desc) }

  include CoverImage
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_playlist, only: %i[ edit destroy update ]

  def index
    if params["type"] == "public"
      @playlists = Playlist.top
      render :top
    else
      @playlists = current_user.playlists
    end
  end

  def show
    @playlists = current_user.playlists
    @playlist = Playlist.where(id: params[:id], is_public: true).first
  end

  def new
    @playlist = current_user.playlists.new
  end

  def create
    @playlist = current_user.playlists.build(playlist_params)

    @playlist.user = current_user

    if @playlist.save
      redirect_to root_path
    else
      render :new, notice: "Failed to create playlist"
    end
  end

  def edit
  end

  def destroy
    @playlist.destroy

    redirect_to root_path, notice: "playlist deleted successfully"
  end

  def update
    @playlist.update(playlist_params)

    redirect_to playlist_path(@playlist), notice: "Updated successfully"
  end

  def add
    @playlist = current_user.playlists.find(playlist_add_params["playlist_id"])

    begin
      @playlist.songs.find(playlist_add_params["song_id"])
      redirect_to root_path 
    rescue
      @song = Song.find(playlist_add_params["song_id"])

      @playlist.songs << @song

      if @playlist.save 
        redirect_to root_path, notice: "Song added!"
      else
        redirect_to root_path, notice: "Couldn't add this song"
      end
    end
  end


  private

  def set_playlist
    @playlist = current_user.playlists.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:color, :name, :cover_image, :is_public)
  end

  def playlist_add_params
    params.require(:playlists_songs).permit(:song_id, :playlist_id)
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<div class="w-5/12">
  <%= form_for playlist do |f| %>
    <%= f.label :name, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
    <%= f.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>


    <%= f.label :color, class: "block my-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
    <%= f.color_field :color %>
    <div class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="user_avatar_help">This color will be used to better style your music.</div>

    <%= f.label :cover_image, class: "block my-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
    <%= f.file_field :cover_image, class: "p-2.5 block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" %>
    <div class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="user_avatar_help">A cover image will be shown while displaying this playlist.</div>

    <%= f.submit "Create Playlist", class: "mt-4 py-2 px-3 bg-accent-200 rounded-md hover:bg-accent-700" %>
  <% end %>
</div>

app/views/playlists/_playlists.html.erb
<% if playlists.present? %>
  <div class="flex space-x-8 scrollable bar pb-2">
    <% playlists.each do |playlist| %>
      <div>
        <%= button_to playlist_path(playlist),
          method: :get,
          class: "rounded-lg w-72 h-72",
          style: "background: no-repeat center/cover url(#{playlist.cover_image_url});" do %> 
          <div 
            class="h-full w-full gradient relative rounded-lg"
            style="--gradient-from-color: <%= hex_color_to_rgba(playlist.color, 0.67) %>; --gradient-to-color: <%= hex_color_to_rgba("#000000", 0.2) %>;"
          >
          <div class="w-full p-4 absolute bottom-0 text-lg font-medium rounded-b-lg" style="background-color: <%= playlist.color %>;">
            <p class="overflow-hidden whitespace-nowrap text-ellipsis">
            <abbr class="no-underline border-none" style="color: <%= text_color_from_bg(playlist.color) %>;" title="<%= playlist.name %>">
              <%= playlist.name %>
            </abbr>
            </p>
          </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="text-grey-50 mb-4">
    You don't have any playlists at this moment.
  </p>

  <%= link_to "Create Playlist", new_playlist_path, class: "mt-4 py-2 px-3 bg-accent-200 rounded-md hover:bg-accent-700" %>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit Playlist</h1>

<%= render "form", playlist: @playlist %>

app/views/playlists/index.html.erb
<div class="py-4 px-6 mb-6">
  <div class="flex items-center">
    <h3 class="mb-3 font-rowdies text-4xl text-accent-400 font-bold mr-2">
      Your Playlists
    </h3>
    <%= link_to new_playlist_path do %>
      <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24"><path fill="#ee6c4d" d="M11 19V13H5V11H11V5H13V11H19V13H13V19Z"/></svg>
    <% end %>
  </div>

  <%= render "playlists", playlists: @playlists %>
</div>

<% if @playlists.present? && @playlists[0].songs.present? %>
  <%= render "components/player", song: @playlists[0].songs[0] %>
<% end %>

app/views/playlists/new.html.erb
<h3 class="mb-3 font-rowdies text-4xl text-accent-400 font-bold">
  Create New Playlist
</h3>

<%= render "form", playlist: @playlist %>

app/views/playlists/show.html.erb
<div class="py-4 px-6 mb-6">
  <div class="mb-3 flex items-center justify-between">
    <div class="flex items-center">
      <h3 class="font-rowdies text-4xl text-accent-400 font-bold mr-2">
        <%= @playlist.name %>
      </h3>
      <%= link_to edit_playlist_path(@playlist) do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24"><path fill="#ee6c4d" d="M5 19H6.4L16.45 8.975L15.75 8.25L15.025 7.55L5 17.6ZM3 21V16.75L16.45 3.325Q17.025 2.75 17.863 2.75Q18.7 2.75 19.275 3.325L20.675 4.75Q21.25 5.325 21.25 6.15Q21.25 6.975 20.675 7.55L7.25 21ZM19.25 6.15 17.85 4.75ZM16.45 8.975 15.75 8.25 15.025 7.55 16.45 8.975Z"/></svg>
      <% end %>
    </div>

    <%= form_for :playlist, method: :patch, data: { controller: "playlist" } do |f| %>
      <%= f.label :is_public, class: "inline-flex relative items-center cursor-pointer" do %>
        <%= f.check_box :is_public, class: "sr-only peer", checked: @playlist.is_public, data: { action: "playlist#submit" } %>
        <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600"></div>
        <span class="ml-3 text-sm font-medium text-gray-900 dark:text-gray-300">
          <% if @playlist.is_public %>
            Public
          <% else %>
            Private
          <% end %>
        </span>
      <% end %>
    <% end %>
  </div>

  <div class="grid grid-cols-4 gap-y-4">
    <% @playlist.songs.latest.each do |song| %>
      <%= render "music/card", song: song, playlist?: true %>
    <% end %>
  </div>

  <% unless @playlist.songs.present? %>
    <p class="text-grey-50 mb-4">
      No songs here.
    </p>
  <% end %>
</div>

<% if @playlist.songs.present? %>
  <%= render "components/player", song: @playlist.songs[0] %>
<% end %>

app/views/playlists/top.html.erb
<div class="py-4 px-6 mb-6">
  <h3 class="mb-3 font-rowdies text-4xl text-accent-400 font-bold">
    Public Playlists
  </h3>

  <%= render "playlists", playlists: @playlists %>
</div>

<% if @playlists.present? && @playlists[0].songs.present? %>
  <%= render "components/player", song: @playlists[0].songs[0] %>
<% end %>