config/routes.rb
Rails.application.routes.draw do
  get '/search', to: "search#index"

  get 'moderation/index'
  patch 'moderation/update/:id', to: "moderation#update"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :albums
  resources :playlists
  post "/playlists/add", to: "playlists#add"
  resources :genres
  resources :music

  root "music#index"

  devise_for :users, 
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :users do
    # fixes redirect on error in form submission on new_user_registration_path
    get '/users', to: 'devise/registrations#new'
    get '/users/profile', to: 'users/profiles#edit'
    post '/users/profile/:id/edit', to: 'users/profiles#update'
  end
end

app/views/layouts/_header.html.erb
<nav class="flex justify-between items-start py-4 px-6">
  <div class="search">
    <form action="/search" method="GET">
      <div class="relative text-gray-600 focus-within:text-gray-400">
        <span class="absolute inset-y-0 left-0 flex items-center pl-2">
          <button type="submit" class="p-1 focus:outline-none focus:shadow-outline">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
          </button>
        </span>
        <input type="search" name="query" class="py-2 text-sm text-white bg-gray-700 rounded-md pl-10 focus:outline-none focus:bg-white focus:text-gray-900" placeholder="Search..." autocomplete="off">
      </div>
    </form>
  </div>
  <div data-controller="profile-badge" class="profile_badge relative">
    <% if current_user %>
      <button 
           class="text-white rounded-full bg-gray-700 hover:bg-gray-800 focus:ring-4 focus:ring-blue-300 font-medium text-sm px-4 py-2.5 text-center inline-flex items-center" 
           type="button" 
           data-action="profile-badge#click"
           data-dropdown-toggle="dropdown"
      >
        <%= image_tag current_user.avatar_url, size: 40, class: "mr-2 rounded-full"  if current_user.avatar.present? %>
        <%= current_user.name %>
        <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
      </button>

      <div data-profile-badge-target="menu" class="hidden position top-16 min-w-[100px] w-full absolute bg-gray-700 text-base z-50 p-1 list-none divide-y divide-gray-100 rounded shadow my-2" id="dropdown">
          <ul aria-labelledby="dropdown">
            <li><%= link_to "Upload a Song", new_music_path, class: "text-sm hover:bg-gray-600 text-white block px-4 py-2" %></li>
            <li><%= link_to "Settings", edit_user_registration_path, class: "text-sm hover:bg-gray-600 text-white block px-4 py-2" %></li>
            <% if current_user.is_admin %>
              <li><%= link_to "Moderate", moderation_index_path, class: "text-sm hover:bg-gray-600 text-white block px-4 py-2" %></li>
            <% end %>
            <li><%= link_to "Sign Out", destroy_user_session_path, class: "text-sm hover:bg-gray-600 text-white block px-4 py-2" %></li>
          </ul>
       </div>
     <% else %>
       <a
           href="<%= new_user_registration_path %>"
           class="text-black rounded-lg bg-white hover:bg-gray-200 focus:ring-4 focus:ring-blue-300 text-sm px-4 py-2.5 text-center inline-flex items-center" 
           type="button" 
      >
        Sign up
      </a>
     <% end %>
  </div>
</nav>

app/views/layouts/_modal.html.erb
<div id="defaultModal" data-modal-target="modal" tabindex="-1" aria-hidden="true" class="flex flex-col items-center justify-center hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
    <div class="relative p-4 w-full max-w-lg h-full md:h-auto">
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
                <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                  <%= title %>
                </h3>
                <button data-action="modal#close" type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="defaultModal">
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>  
                </button>
            </div>
            <div class="p-6 space-y-6">
              <%= yield %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar" class="py-4 px-6 bg-dark h-full">
  <div class="mb-6">
    <a href="<%= root_path %>" data-turbo="false" >
      <div class="flex flex-row items-center">
      <svg width="66" height="62" viewBox="0 0 66 62" fill="none" xmlns="http://www.w3.org/2000/svg">
        <ellipse cx="13.6667" cy="15.5" rx="13.6667" ry="15.5" fill="#C4C4C4"/>
        <path d="M30.6711 51.1339L14.9383 26.6965C11.5109 21.3727 15.3332 14.366 21.6649 14.366H51.9333C58.138 14.366 61.9808 21.123 58.8089 26.4557L44.2732 50.8931C41.2356 56 33.8876 56.1301 30.6711 51.1339Z" stroke="#EE6C4D"/>
        <ellipse cx="50.9999" cy="39.6951" rx="13.6667" ry="15.5" fill="#C4C4C4"/>
      </svg>
      <span class="mx-1"></span>
      <h2 class="text-accent-400 text-4xl font-rowdies font-bold">BRANTI</h2>
      </div>
    </a>
  </div>
  <div class="mb-6">
    <ul>
      <li><%= link_to "Albums", albums_path, class: "hover:text-accent-200" %></li>
      <li><%= link_to "Genres", genres_path, class: "hover:text-accent-200" %></li>
      <li><%= link_to "Public Playlists", "/playlists?type=public", class: "hover:text-accent-200" %></li>
    </ul>
  </div>
  <div>
    <div class="mb-3 flex justify-between items-center">
      <%= link_to "Playlists", playlists_path, class: "font-rowdies text-3xl text-accent-400 font-bold" %>
      <%= link_to new_playlist_path, class: "text-4xl py-2 px-3 text-center text-accent-400 rounded-md hover:scale-110" do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24"><path fill="#ee6c4d" d="M11 19V13H5V11H11V5H13V11H19V13H13V19Z"/></svg>
      <% end %>
    </div>

    <% unless current_user&.playlists&.where&.not(id: nil).present? %>
      <div class="flex flex-col justify-center">
      <p class="text-grey-50">
        You have no playlists.
      </p>
      <%= link_to "Create Playlist", new_playlist_path, class: "mt-4 py-2 px-3 bg-accent-200 text-center rounded-md hover:bg-accent-700" %>
    <% else %>
      <ul>
        <% current_user.playlists&.where&.not(id: nil).each do |playlist| %>
          <li><%= link_to playlist.name, playlist_path(playlist), class: "hover:text-accent-200" %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Branti</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rowdies:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="h-screen relative overflow-hidden font-montsterrat">
    <%# TODO: <%= flash[:notice] if flash[:notice] %1> %>
    <%= render "layouts/sidebar" %>
    <main class="py-4 px-6 relative overflow-auto bar">
      <%= render "layouts/header" %>
      <%= yield %>
    </main>
  </body>
</html>